[tool.poetry]
name = "aci-crc-fcs-checker"
version = "0.1.0"
description = "Testing"
authors = ["TomMik <thomas_mikolajewski@yahoo.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
